name: Sync to Azure DevOps

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2

    - name: Push to Azure DevOps
      run: |
        git config user.email "Luiz-AVcruz@baracubaba.com.br"
        git config user.name "Luiz Augusto Vitorino Cruz"
        git remote add azure https://Baracubaba@dev.azure.com/Baracubaba/Con-Affetto/_git/Con-Affetto
        git push azure HEAD:refs/heads/${{ github.ref_name }}
        git push azure --tags
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
