name: Sync to Azure DevOps

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Faz um clone "deep" do repositório

    - name: Push to Azure DevOps
      run: |
        git remote add azure https://Baracubaba:${{ secrets.AZURE_DEVOPS_PAT }}@dev.azure.com/Baracubaba/Con-Affetto/_git/Con-Affetto
        git push azure HEAD:refs/heads/main --force  # Força o push
        git push azure --tags
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
